package com.lishuiwan.service;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper; import com.baomidou.mybatisplus.core.conditions.update.LambdaUpdateWrapper;
import com.lishuiwan.common.*; import com.lishuiwan.domain.*; import com.lishuiwan.mapper.*;
import org.springframework.http.HttpStatus; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service;
import java.math.BigDecimal; import java.time.LocalDateTime; import java.util.*;

@Service
public class AdminService {
  private final CardProductMapper products; private final ActivityMapper activities; private final MemberMapper members; private final OrderMapper orders;
  private final VerificationMapper verifications; private final AdminUserMapper admins; private final OperationLogMapper logs; private final Jsons json; private final PasswordEncoder passwords; private final OrderItemMapper items;
  public AdminService(CardProductMapper products,ActivityMapper activities,MemberMapper members,OrderMapper orders,VerificationMapper verifications,AdminUserMapper admins,OperationLogMapper logs,Jsons json,PasswordEncoder passwords,OrderItemMapper items){this.products=products;this.activities=activities;this.members=members;this.orders=orders;this.verifications=verifications;this.admins=admins;this.logs=logs;this.json=json;this.passwords=passwords;this.items=items;}
  public CardProduct saveProduct(Long id,Map<String,Object> b,long adminId){CardProduct p=id==null?new CardProduct():products.selectById(id);if(p==null)throw BizException.notFound("卡商品");p.setName(text(b,"name"));p.setCategory(text(b,"category"));p.setCover(nullable(b,"cover"));p.setBenefits(json.write(b.get("benefits")));p.setPrice(money(b,"price"));p.setSalePrice(money(b,"salePrice"));p.setActivityPrice(optionalMoney(b,"activityPrice"));p.setActivityStartAt(date(b,"activityStartAt"));p.setActivityEndAt(date(b,"activityEndAt"));p.setValidDays(Integer.parseInt(b.get("validDays").toString()));p.setRules(nullable(b,"rules"));p.setStatus(Integer.parseInt(String.valueOf(b.getOrDefault("status",0))));p.setSort(Integer.parseInt(String.valueOf(b.getOrDefault("sort",0))));validateProduct(p,b.get("benefits"));if(id==null)products.insert(p);else products.updateById(p);log(adminId,id==null?"create_product":"update_product","product",p.getId(),b);return p;}
  private void validateProduct(CardProduct p,Object benefits){if(p.getName().isBlank()||p.getValidDays()<=0||p.getPrice().compareTo(p.getSalePrice())<0||p.getSalePrice().compareTo(BigDecimal.ZERO)<=0)throw new BizException(40002,"商品价格或有效期不合法",HttpStatus.BAD_REQUEST);if(!(benefits instanceof List<?> l)||l.isEmpty())throw new BizException(40002,"至少配置一项权益",HttpStatus.BAD_REQUEST);Set<String> ids=new HashSet<>();for(Object o:l){if(!(o instanceof Map<?,?> m)||m.get("benefitId")==null||m.get("item")==null||m.get("type")==null||!ids.add(m.get("benefitId").toString()))throw new BizException(40002,"权益配置不完整或 benefitId 重复",HttpStatus.BAD_REQUEST);}if(p.getActivityPrice()!=null&&(p.getActivityStartAt()==null||p.getActivityEndAt()==null||!p.getActivityStartAt().isBefore(p.getActivityEndAt())||p.getActivityPrice().compareTo(BigDecimal.ZERO)<=0||p.getActivityPrice().compareTo(p.getSalePrice())>0))throw new BizException(40002,"活动价配置不合法",HttpStatus.BAD_REQUEST);}
  public void productStatus(long id,int status,long adminId){CardProduct p=products.selectById(id);if(p==null)throw BizException.notFound("卡商品");p.setStatus(status==1?1:0);products.updateById(p);log(adminId,"product_status","product",id,Map.of("status",p.getStatus()));}
  public void deleteProduct(long id,long adminId){if(products.deleteById(id)==0)throw BizException.notFound("卡商品");log(adminId,"delete_product","product",id,Map.of());}
  public Activity saveActivity(Long id,Activity a,long adminId){if(a.getTitle()==null||a.getStartAt()==null||a.getEndAt()==null||!a.getStartAt().isBefore(a.getEndAt()))throw new BizException(40002,"活动信息不完整",HttpStatus.BAD_REQUEST);if(id==null)activities.insert(a);else{a.setId(id);activities.updateById(a);}log(adminId,id==null?"create_activity":"update_activity","activity",a.getId(),Map.of("title",a.getTitle()));return a;}
  public void grant(long adminId,long memberId,String role){if(!Set.of("customer","verifier","admin").contains(role))throw new BizException(40002,"角色不合法",HttpStatus.BAD_REQUEST);Member m=members.selectById(memberId);if(m==null)throw BizException.notFound("会员");String before=m.getStaffRole();m.setStaffRole(role);members.updateById(m);log(adminId,"grant_role","member",memberId,Map.of("before",before,"after",role));}
  public AdminUser saveAdmin(Long id,String username,String password,String name,Integer status,long operator){AdminUser a=id==null?new AdminUser():admins.selectById(id);if(a==null)throw BizException.notFound("管理员");a.setUsername(username);a.setName(name);a.setStatus(status==null?0:status);if(password!=null&&!password.isBlank()){if(password.length()<12)throw new BizException(40002,"密码至少 12 位",HttpStatus.BAD_REQUEST);a.setPassword(passwords.encode(password));}if(id==null&&a.getPassword()==null)throw new BizException(40002,"请输入密码",HttpStatus.BAD_REQUEST);if(id==null)admins.insert(a);else admins.updateById(a);log(operator,id==null?"create_admin":"update_admin","admin_user",a.getId(),Map.of("username",username));return a;}
  public Map<String,Object> overview(){LocalDateTime start=LocalDateTime.now().toLocalDate().atStartOfDay();List<OrderEntity> paid=orders.selectList(new LambdaQueryWrapper<OrderEntity>().eq(OrderEntity::getPayStatus,1));BigDecimal sales=paid.stream().map(OrderEntity::getPaidAmount).filter(Objects::nonNull).reduce(BigDecimal.ZERO,BigDecimal::add);return Map.of("sales",sales,"orders",paid.size(),"verifications",verifications.selectCount(null),"members",members.selectCount(null),"todayNewMembers",members.selectCount(new LambdaQueryWrapper<Member>().ge(Member::getCreatedAt,start)));}
  public List<Map<String,Object>> salesTrend(){return orders.selectList(new LambdaQueryWrapper<OrderEntity>().eq(OrderEntity::getPayStatus,1).orderByAsc(OrderEntity::getPaidAt)).stream().collect(java.util.stream.Collectors.groupingBy(o->o.getPaidAt().toLocalDate().toString(),LinkedHashMap::new,java.util.stream.Collectors.reducing(BigDecimal.ZERO,OrderEntity::getPaidAmount,BigDecimal::add))).entrySet().stream().map(e->Map.<String,Object>of("date",e.getKey(),"amount",e.getValue())).toList();}
  @SuppressWarnings("unchecked") public List<Map<String,Object>> categoryReport(){Map<String,Long> grouped=new LinkedHashMap<>();for(OrderEntity o:orders.selectList(new LambdaQueryWrapper<OrderEntity>().eq(OrderEntity::getPayStatus,1))){OrderItem item=items.selectOne(new LambdaQueryWrapper<OrderItem>().eq(OrderItem::getOrderId,o.getId()));if(item!=null){Map<String,Object>s=json.read(item.getProductSnapshot(),Map.class);grouped.merge(String.valueOf(s.getOrDefault("category","其他")),1L,Long::sum);}}return grouped.entrySet().stream().map(e->Map.<String,Object>of("category",e.getKey(),"count",e.getValue())).toList();}
  private void log(long operator,String action,String type,Long target,Object detail){OperationLog l=new OperationLog();l.setOperatorType("admin_user");l.setOperatorId(operator);l.setAction(action);l.setTargetType(type);l.setTargetId(target);l.setDetail(json.write(detail));logs.insert(l);}
  private String text(Map<String,Object>b,String k){String v=nullable(b,k);if(v==null||v.isBlank())throw new BizException(40002,k+"不能为空",HttpStatus.BAD_REQUEST);return v;}
  private String nullable(Map<String,Object>b,String k){Object v=b.get(k);return v==null?null:v.toString();}
  private BigDecimal money(Map<String,Object>b,String k){if(b.get(k)==null)throw new BizException(40002,k+"不能为空",HttpStatus.BAD_REQUEST);return new BigDecimal(b.get(k).toString());}
  private BigDecimal optionalMoney(Map<String,Object>b,String k){return b.get(k)==null||b.get(k).toString().isBlank()?null:new BigDecimal(b.get(k).toString());}
  private LocalDateTime date(Map<String,Object>b,String k){return b.get(k)==null||b.get(k).toString().isBlank()?null:LocalDateTime.parse(b.get(k).toString());}
}
