package com.lishuiwan.service;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.lishuiwan.common.*; import com.lishuiwan.config.AppProperties; import com.lishuiwan.domain.*; import com.lishuiwan.mapper.*;
import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal; import java.time.LocalDateTime; import java.util.*;

@Service
public class OrderService {
  private final OrderMapper orders; private final OrderItemMapper items; private final MembershipCardMapper cards; private final NotificationMapper notifications;
  private final CatalogService catalog; private final IdempotencyService idem; private final Jsons json; private final AppProperties p;
  public OrderService(OrderMapper orders,OrderItemMapper items,MembershipCardMapper cards,NotificationMapper notifications,CatalogService catalog,IdempotencyService idem,Jsons json,AppProperties p){this.orders=orders;this.items=items;this.cards=cards;this.notifications=notifications;this.catalog=catalog;this.idem=idem;this.json=json;this.p=p;}
  public Map<String,Object> create(long memberId,long productId,String requestNo){return idem.execute("member",memberId,"create_order",requestNo,Map.of("productId",productId),()->createInternal(memberId,productId,"wechat",null,null));}
  public Map<String,Object> mockPay(long memberId,String orderNo,String requestNo){if(!p.isMockPaymentEnabled())throw new BizException(40303,"模拟支付未启用",HttpStatus.FORBIDDEN);return idem.execute("member",memberId,"mock_pay",requestNo,Map.of("orderNo",orderNo),()->{OrderEntity o=orders.selectForUpdate(orderNo);if(o==null)throw BizException.notFound("订单");if(!o.getMemberId().equals(memberId))throw BizException.forbidden();if(o.getPayStatus()==1)return paymentResult(o);if(o.getPayStatus()!=0||!o.getExpireAt().isAfter(LocalDateTime.now()))throw new BizException(40902,"订单已关闭",HttpStatus.CONFLICT);return paySuccess(o,null);});}
  Map<String,Object> cashOnce(long operatorId,long memberId,long productId,BigDecimal paidAmount){if(paidAmount==null||paidAmount.compareTo(BigDecimal.ZERO)<=0)throw new BizException(40002,"实收金额必须大于 0",HttpStatus.BAD_REQUEST);return createInternal(memberId,productId,"cash",paidAmount,operatorId);}
  private Map<String,Object> createInternal(long memberId,long productId,String method,BigDecimal paidAmount,Long operator){CardProduct product=catalog.requireProduct(productId,true);BigDecimal price=catalog.currentPrice(product);OrderEntity o=new OrderEntity();o.setOrderNo(Ids.orderNo());o.setMemberId(memberId);o.setPayableAmount(price);o.setPaidAmount(paidAmount);o.setPayMethod(method);o.setPayStatus("cash".equals(method)?1:0);o.setOperatorMemberId(operator);o.setExpireAt(LocalDateTime.now().plusMinutes(15));if(o.getPayStatus()==1)o.setPaidAt(LocalDateTime.now());orders.insert(o);OrderItem item=new OrderItem();item.setOrderId(o.getId());item.setProductId(productId);item.setQuantity(1);item.setUnitPrice(price);item.setProductSnapshot(json.write(catalog.view(product)));items.insert(item);if(o.getPayStatus()==1){MembershipCard card=createCard(o,item);notifyIssue(memberId,o.getId(),product.getName());return Map.of("orderId",o.getId(),"orderNo",o.getOrderNo(),"cardId",card.getId(),"status","paid");}return Map.of("orderId",o.getId(),"orderNo",o.getOrderNo(),"status","pending","payableAmount",price);}
  @Transactional public Map<String,Object> paySuccess(OrderEntity o,String transactionId){if(o.getPayStatus()==1)return paymentResult(o);o.setPayStatus(1);o.setPaidAmount(o.getPayableAmount());o.setPaidAt(LocalDateTime.now());o.setTransactionId(transactionId);orders.updateById(o);OrderItem item=items.selectOne(new LambdaQueryWrapper<OrderItem>().eq(OrderItem::getOrderId,o.getId()));MembershipCard card=createCard(o,item);@SuppressWarnings("unchecked")Map<String,Object> snapshot=json.read(item.getProductSnapshot(),Map.class);notifyIssue(o.getMemberId(),o.getId(),String.valueOf(snapshot.get("name")));return Map.of("orderId",o.getId(),"orderNo",o.getOrderNo(),"cardId",card.getId(),"status","paid");}
  @Transactional public Map<String,Object> paySuccessLocked(String orderNo,String transactionId){OrderEntity o=orders.selectForUpdate(orderNo);if(o==null)throw BizException.notFound("订单");return paySuccess(o,transactionId);}
  private MembershipCard createCard(OrderEntity o,OrderItem item){return createCardFromSnapshot(o,item);}
  @SuppressWarnings("unchecked") private MembershipCard createCardFromSnapshot(OrderEntity o,OrderItem item){Map<String,Object> snapshot=json.read(item.getProductSnapshot(),Map.class);List<Map<String,Object>> source=(List<Map<String,Object>>)snapshot.get("benefits");List<Map<String,Object>> remaining=new ArrayList<>();for(Map<String,Object>b:source){Map<String,Object>x=new LinkedHashMap<>(b);if(!"unlimited".equals(String.valueOf(b.get("type"))))x.put("remaining",b.get("total"));remaining.add(x);}MembershipCard c=new MembershipCard();c.setMemberId(o.getMemberId());c.setProductId(item.getProductId());c.setOrderItemId(item.getId());c.setBenefitsRemaining(json.write(remaining));c.setValidFrom(o.getPaidAt());c.setValidUntil(o.getPaidAt().plusDays(Integer.parseInt(snapshot.get("validDays").toString())));c.setStatus("unused");c.setVersion(0);cards.insert(c);return c;}
  private void notifyIssue(long memberId,long orderId,String name){Notification n=new Notification();n.setMemberId(memberId);n.setType("issue");n.setTitle("发卡成功");n.setContent("您已获得「"+name+"」");n.setRefId(orderId);n.setIsRead(0);n.setPushStatus("pending");n.setPushAttempts(0);notifications.insert(n);}
  private Map<String,Object> paymentResult(OrderEntity o){MembershipCard c=cards.selectOne(new LambdaQueryWrapper<MembershipCard>().inSql(MembershipCard::getOrderItemId,"select id from t_order_item where order_id="+o.getId()));return Map.of("orderId",o.getId(),"orderNo",o.getOrderNo(),"cardId",c==null?0:c.getId(),"status","paid");}
  public OrderEntity requireOrder(String no){OrderEntity o=orders.selectOne(new LambdaQueryWrapper<OrderEntity>().eq(OrderEntity::getOrderNo,no));if(o==null)throw BizException.notFound("订单");return o;}
  public List<Map<String,Object>> memberOrders(long memberId){return orders.selectList(new LambdaQueryWrapper<OrderEntity>().eq(OrderEntity::getMemberId,memberId).orderByDesc(OrderEntity::getId)).stream().map(this::view).toList();}
  @SuppressWarnings("unchecked") public Map<String,Object> view(OrderEntity o){Map<String,Object> v=new LinkedHashMap<>();v.put("id",o.getId());v.put("orderNo",o.getOrderNo());v.put("memberId",o.getMemberId());v.put("payableAmount",o.getPayableAmount());v.put("paidAmount",o.getPaidAmount());v.put("payMethod",o.getPayMethod());v.put("payStatus",o.getPayStatus());v.put("paidAt",o.getPaidAt());v.put("createdAt",o.getCreatedAt());OrderItem item=items.selectOne(new LambdaQueryWrapper<OrderItem>().eq(OrderItem::getOrderId,o.getId()));if(item!=null)v.put("item",json.read(item.getProductSnapshot(),Map.class));return v;}
  public List<MembershipCard> memberCards(long memberId){return cards.selectList(new LambdaQueryWrapper<MembershipCard>().eq(MembershipCard::getMemberId,memberId).orderByDesc(MembershipCard::getId));}
  public List<Verification> cardVerifications(long memberId,long cardId,VerificationMapper verificationMapper){MembershipCard c=cards.selectById(cardId);if(c==null||!c.getMemberId().equals(memberId))throw BizException.notFound("权益卡");return verificationMapper.selectList(new LambdaQueryWrapper<Verification>().eq(Verification::getCardId,cardId).orderByDesc(Verification::getId));}
}
