package com.lishuiwan.controller;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.lishuiwan.common.*; import com.lishuiwan.config.AppProperties; import com.lishuiwan.domain.*; import com.lishuiwan.mapper.*; import com.lishuiwan.service.*;
import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile;
import java.nio.file.*; import java.time.LocalDateTime; import java.util.*;

@RestController @RequestMapping("/api/admin")
public class AdminController {
  private final AdminService service; private final CatalogService catalog; private final ActivityMapper activities; private final MemberMapper members;
  private final OrderMapper orders; private final VerificationMapper verifications; private final AdminUserMapper admins; private final AppProperties properties; private final OrderService orderService;
  public AdminController(AdminService service,CatalogService catalog,ActivityMapper activities,MemberMapper members,OrderMapper orders,VerificationMapper verifications,AdminUserMapper admins,AppProperties properties,OrderService orderService){this.service=service;this.catalog=catalog;this.activities=activities;this.members=members;this.orders=orders;this.verifications=verifications;this.admins=admins;this.properties=properties;this.orderService=orderService;}
  public record StatusRequest(@NotNull Integer status){}
  public record StaffRequest(@NotNull Long memberId,@NotBlank String staffRole){}
  public record AdminRequest(@NotBlank String username,String password,@NotBlank String name,Integer status){}
  @GetMapping("/products") public ApiResponse<List<Map<String,Object>>> products(){return ApiResponse.ok(catalog.products(false));}
  @PostMapping("/products") public ApiResponse<CardProduct> createProduct(@RequestBody Map<String,Object> body){return ApiResponse.ok(service.saveProduct(null,body,RequestActor.adminId()));}
  @PutMapping("/products/{id}") public ApiResponse<CardProduct> updateProduct(@PathVariable long id,@RequestBody Map<String,Object> body){return ApiResponse.ok(service.saveProduct(id,body,RequestActor.adminId()));}
  @PutMapping("/products/{id}/status") public ApiResponse<Void> productStatus(@PathVariable long id,@Valid @RequestBody StatusRequest r){service.productStatus(id,r.status(),RequestActor.adminId());return ApiResponse.ok(null);}
  @DeleteMapping("/products/{id}") public ApiResponse<Void> deleteProduct(@PathVariable long id){service.deleteProduct(id,RequestActor.adminId());return ApiResponse.ok(null);}
  @GetMapping("/activities") public ApiResponse<List<Activity>> activityList(){return ApiResponse.ok(activities.selectList(new LambdaQueryWrapper<Activity>().orderByAsc(Activity::getSort)));}
  @PostMapping("/activities") public ApiResponse<Activity> createActivity(@RequestBody Activity a){return ApiResponse.ok(service.saveActivity(null,a,RequestActor.adminId()));}
  @PutMapping("/activities/{id}") public ApiResponse<Activity> updateActivity(@PathVariable long id,@RequestBody Activity a){return ApiResponse.ok(service.saveActivity(id,a,RequestActor.adminId()));}
  @DeleteMapping("/activities/{id}") public ApiResponse<Void> deleteActivity(@PathVariable long id){service.deleteActivity(id,RequestActor.adminId());return ApiResponse.ok(null);}
  @GetMapping("/members") public ApiResponse<List<Map<String,Object>>> memberList(@RequestParam(required=false) String keyword){LambdaQueryWrapper<Member> q=new LambdaQueryWrapper<Member>().orderByDesc(Member::getId).last("limit 500");if(keyword!=null&&!keyword.isBlank())q.and(x->x.like(Member::getPhone,keyword).or().like(Member::getNickname,keyword));return ApiResponse.ok(members.selectList(q).stream().map(this::memberView).toList());}
  @GetMapping("/members/{id}") public ApiResponse<Map<String,Object>> member(@PathVariable long id){Member m=members.selectById(id);if(m==null)throw BizException.notFound("会员");return ApiResponse.ok(memberView(m));}
  @GetMapping("/orders") public ApiResponse<List<Map<String,Object>>> orderList(){return ApiResponse.ok(orders.selectList(new LambdaQueryWrapper<OrderEntity>().orderByDesc(OrderEntity::getId).last("limit 1000")).stream().map(orderService::view).toList());}
  @GetMapping("/orders/{id}") public ApiResponse<Map<String,Object>> order(@PathVariable long id){OrderEntity o=orders.selectById(id);if(o==null)throw BizException.notFound("订单");return ApiResponse.ok(orderService.view(o));}
  @GetMapping("/verifications") public ApiResponse<List<Verification>> verificationList(){return ApiResponse.ok(verifications.selectList(new LambdaQueryWrapper<Verification>().orderByDesc(Verification::getId).last("limit 1000")));}
  @GetMapping("/staff") public ApiResponse<List<Map<String,Object>>> staff(){return ApiResponse.ok(members.selectList(new LambdaQueryWrapper<Member>().ne(Member::getStaffRole,"customer").orderByDesc(Member::getId)).stream().map(this::memberView).toList());}
  @PostMapping("/staff") public ApiResponse<Void> staff(@Valid @RequestBody StaffRequest r){service.grant(RequestActor.adminId(),r.memberId(),r.staffRole());return ApiResponse.ok(null);}
  @DeleteMapping("/staff/{memberId}") public ApiResponse<Void> revoke(@PathVariable long memberId){service.grant(RequestActor.adminId(),memberId,"customer");return ApiResponse.ok(null);}
  @GetMapping("/reports/overview") public ApiResponse<Map<String,Object>> overview(){return ApiResponse.ok(service.overview());}
  @GetMapping("/reports/sales") public ApiResponse<List<Map<String,Object>>> sales(){return ApiResponse.ok(service.salesTrend());}
  @GetMapping("/reports/category") public ApiResponse<List<Map<String,Object>>> category(){return ApiResponse.ok(service.categoryReport());}
  @GetMapping("/admin-users") public ApiResponse<List<Map<String,Object>>> adminList(){return ApiResponse.ok(admins.selectList(new LambdaQueryWrapper<AdminUser>().orderByAsc(AdminUser::getId)).stream().map(a->Map.<String,Object>of("id",a.getId(),"username",a.getUsername(),"name",a.getName(),"status",a.getStatus())).toList());}
  @PostMapping("/admin-users") public ApiResponse<AdminUser> createAdmin(@Valid @RequestBody AdminRequest r){return ApiResponse.ok(service.saveAdmin(null,r.username(),r.password(),r.name(),r.status(),RequestActor.adminId()));}
  @PutMapping("/admin-users/{id}") public ApiResponse<AdminUser> updateAdmin(@PathVariable long id,@Valid @RequestBody AdminRequest r){return ApiResponse.ok(service.saveAdmin(id,r.username(),r.password(),r.name(),r.status(),RequestActor.adminId()));}
  @DeleteMapping("/admin-users/{id}") public ApiResponse<Void> disableAdmin(@PathVariable long id){if(id==RequestActor.adminId())throw new BizException(40002,"不能禁用当前账号",HttpStatus.BAD_REQUEST);service.disableAdmin(id,RequestActor.adminId());return ApiResponse.ok(null);}
  @PostMapping("/upload") public ApiResponse<Map<String,Object>> upload(@RequestPart("file") MultipartFile file) throws Exception {if(file.isEmpty()||file.getSize()>properties.getUpload().getMaxBytes())throw new BizException(40002,"文件为空或超过大小限制",HttpStatus.BAD_REQUEST);String content=file.getContentType();if(content==null||!Set.of("image/jpeg","image/png","image/webp").contains(content))throw new BizException(40002,"仅支持 JPG、PNG、WebP",HttpStatus.BAD_REQUEST);byte[] head=file.getBytes();if(!isImage(head,content))throw new BizException(40002,"图片内容不合法",HttpStatus.BAD_REQUEST);String ext=switch(content){case"image/jpeg"->".jpg";case"image/png"->".png";default->".webp";};String name=UUID.randomUUID().toString().replace("-","")+ext;Path dir=Path.of(properties.getUpload().getDirectory()).toAbsolutePath().normalize();Files.createDirectories(dir);Files.write(dir.resolve(name),head,StandardOpenOption.CREATE_NEW);return ApiResponse.ok(Map.of("url",properties.getUpload().getUrlPrefix()+name));}
  @GetMapping(value="/orders/export",produces="text/csv;charset=UTF-8") public ResponseEntity<byte[]> exportOrders(){StringBuilder b=new StringBuilder("订单号,会员ID,实收金额,支付方式,状态,支付时间\n");for(OrderEntity o:orders.selectList(new LambdaQueryWrapper<OrderEntity>().orderByDesc(OrderEntity::getId))){b.append(o.getOrderNo()).append(',').append(o.getMemberId()).append(',').append(o.getPaidAmount()==null?"":o.getPaidAmount()).append(',').append(o.getPayMethod()).append(',').append(o.getPayStatus()).append(',').append(o.getPaidAt()==null?"":o.getPaidAt()).append('\n');}byte[] bytes=("\uFEFF"+b).getBytes(java.nio.charset.StandardCharsets.UTF_8);return ResponseEntity.ok().header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=orders.csv").body(bytes);}
  private boolean isImage(byte[] b,String type){if(b.length<12)return false;return switch(type){case"image/jpeg"->(b[0]&255)==0xFF&&(b[1]&255)==0xD8;case"image/png"->(b[0]&255)==0x89&&b[1]==0x50&&b[2]==0x4E&&b[3]==0x47;case"image/webp"->new String(b,0,4).equals("RIFF")&&new String(b,8,4).equals("WEBP");default->false;};}
  private Map<String,Object> memberView(Member m){Map<String,Object> v=new LinkedHashMap<>();v.put("id",m.getId());v.put("phone",m.getPhone());v.put("nickname",m.getNickname());v.put("avatar",m.getAvatar());v.put("staffRole",m.getStaffRole());v.put("level",m.getLevel());v.put("points",m.getPoints());v.put("status",m.getStatus());v.put("createdAt",m.getCreatedAt());return v;}
}
